name: (â–¶) Start Hotfix

on: workflow_dispatch

jobs:
    release:
        uses: sitepark/github-project-workflow/.github/workflows/composer-start-hotfix.yml@main
        with:
            botName: "sitepark-bot"
            botEmail: "opensource@sitepark.com"
        secrets:
            # Sitepark-BOT personal access token
            BOT_PAT: ${{ secrets.BOT_PAT }}
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
