name: (â–¶) Start Hotfix

on: workflow_dispatch

jobs:
    release:
        uses: sitepark/github-project-workflow/.github/workflows/composer-start-hotfix.yml@main
        with:
            phpVersion: "8.4"
            ref: ${{ github.ref }}
